### ISSUE TITLE
in/out/error to lms::logging

### ISSUE THREAD

**Issue by Phibedy** [Phibedy/LMS#107]
Atm we throw in/out/error away, as some libraries don't provide a logging interface they use them to print errors. For example [ximea](https://www.ximea.com/support/wiki/apis/XiAPI). We don't get informed if it goes wrong. Therefore we should redirect out to `lms::logging::info` and error to `lms::logging::error`

**Comment by Phibedy** [comment]
We should add this feature next as I also need it for [dso](https://github.com/lms-org/dso)

**Comment by syxolk** [comment]
Fixed with 0638d5accd
