### ISSUE TITLE
publish method for datachannels

### ISSUE THREAD

**Issue by Phibedy** [Phibedy/LMS#129]
We could add `publish` and `hasNewData` methods to dataChannel:
```
void publish(lms::Time t= lms::Time::now())
```
It would set some internal time value.
```
bool hasNewData()
```
Would check the internal time value and return true after publish has been called only once for each module.

**Comment by syxolk** [comment]
Is it really necessary to save a timestamp here? (Do you need the timestamp?)

**Comment by syxolk** [comment]
It would make sense to have the `publish()`-method only for `WriteDataChannel` and `hasNewData()` only for `ReadDataChannel`.
