### ISSUE TITLE
Datachannel serialization

### ISSUE THREAD

**Issue by syxolk** [Phibedy/LMS#16]
Implement some kind of data channel serialization to send/receive and store/load data channels. Suggested is a super class Serializable that provides serialize() and deserialize().

Use [cereal](http://uscilab.github.io/cereal/index.html) or [boost serialization](http://www.boost.org/doc/libs/1_57_0/libs/serialization/doc/index.html) to circumvent problems with endianess and integer bit length.

**Comment by mherb** [comment]
Cereal looks very neat! Probably much easier than building custom serializers from scratch..

**Comment by syxolk** [comment]
Closed with commit [Implemented DataManager::(de)serializeChannel and get*Access](https://github.com/Phibedy/LMS/commit/d7f72d8d970eb8de4c7b39a5c2419e2c3fe182b5)
