### ISSUE TITLE
configfile->datachannel update

### ISSUE THREAD

**Issue by Phibedy** [Phibedy/LMS#19]
Detect if a configfile was modified and update the datachannel.

**Comment by syxolk** [comment]
Implemented with [commit](https://github.com/Phibedy/LMS/commit/191095d651ba2c12ff1c8caaf9ee28fb984196d3).

Still missing:
- Enable modules
- Load Module definitions (-> available modules)
- Changes in data channel mapping
- Reload *.so files

**Comment by Phibedy** [comment]
Don't think that we should implement the missing parts
