### ISSUE TITLE
Config Repos

### ISSUE THREAD

**Issue by syxolk** [Phibedy/LMS#29]
While config repos being already implemented there are still open issues:
- loading and providing xml nodes to modules #Won't be done atm
- transparent data channel mapping #DONE
- rework console parameter "-c" #DONE
- relative paths in <include src="..." /> and <config src="..." /> #DONE
- improve libpath/libname #Done

**Comment by Phibedy** [comment]
console parameter:
As discussed yesterday we could:
- set the framework-config-name
- we could set the framework-suffix and use that suffix for all configs included:
  - Pro - You could have different module-configs using one framework-config
  - Con - It might be over-engineered and confusing
    I would go for the first approach and if we need it we could still and another parameter to meet requirements for the second option.

Paths:
"/path" for absolute paths,
"path" for relative paths
"$path" for  paths relative to the configs directory (of course $ could be changed to any letter that isn't use in filenames)
Another approach would be to add a attr. to the xml-node like "dest" = rel | abs | conf
by default the dest would be relative (rel). Maybe that is overkill.

What would happen if the change the xml-nodes during execution [related to that](https://github.com/Phibedy/LMS/issues/30)?
