### ISSUE TITLE
Move ConfigurationManager instance to Framework

### ISSUE THREAD

**Issue by syxolk** [Phibedy/LMS#3]
The lms::DataManager class contained an instance to lms::ConfigurationManager:

``` c++
//Ins framework
ConfigurationManager conf_mgr;

ConfigFile *DataManager::config(const char* configName) {
    return conf_mgr->getConfig(configName);
}

ConfigurationManager *cfgMgr() { return conf_mgr; }
```

Move this somehow to lms::Framework.

**Comment by Phibedy** [comment]
As we will go for xml (maybe json) as standard for config files this could be moved into a library as it's not necessary for the core

**Comment by Phibedy** [comment]
Done
