### ISSUE TITLE
New Module cycle

### ISSUE THREAD

**Issue by syxolk** [Phibedy/LMS#30]
I suggest a new module cycle including a loadConfig() method. This new method is invoked after initialize() to read the config after start up and after changes to any config files. As a result, all config loading code inside initialize() must be moved to the new loadConfig() method.

For the transition phase class Module implements loadConfig() with an empty body. For convenience the method could get a pointer to lms::type::ModuleConfig.

The old ideas were:
- If any config file changes, disable and enable all modules that need new config data.
- OR: If any config file changes, invoke reset() on the module. The reset would be usually implemented to close and reopen all resources (file descriptors, socket, etc.). This is quite inefficient and should be avoided.

**Comment by Phibedy** [comment]
In the old "config-system" I planed to just change the DataChannel as configs were datachannels. So if you don't copy data from the config and use the reference you should have been fine. Of course that would have only worked for simple configs properly.
I am not sure about where we should request DataChannels, if they are requested from the loadConfig() method, their name could change.
Would the loadConfig-function also handle changed string-mapping-values?
