### ISSUE TITLE
lmslib

### ISSUE THREAD

**Issue by syxolk** [Phibedy/LMS#49]
Test results for the lmslib branch on LMS and lms_config_repo on Ubuntu 14.04 with GCC 4.8.4:
### As static lib, with -fPIC, with RTLD_DEEPBIND:
- Signal Handler works
### As static lib, with -fPIC, without RTLD_DEEPBIND:
- SignalHandler works
- LMS exits with:

```
*** Error in `./lms': double free or corruption (fasttop): 0x0000000001a0ba60 ***
zsh: abort (core dumped)  ./lms --profiling
```
### As static lib, without -fPIC:
- Compiling fails with:

```
Linking CXX shared module libclock_test.so
/usr/bin/ld: ../../../LMS/lms/liblms_lib.a(module.cpp.o): Die Umlagerung von 
../../../LMS/lms/liblms_lib.a: error adding symbols: Ungültiger Wert
collect2: error: ld returned 1 exit status
make[2]: *** [external/modules/clock_test/libclock_test.so] Fehler 1
make[1]: *** [external/modules/clock_test/CMakeFiles/clock_test.dir/all] Fehler 2
make[1]: *** Auf noch nicht beendete Prozesse wird gewartet …
```
### As shared lib, with -fPIC, with RTLD_DEEPBIND:
- SignalHandler works
### As shared lib, with -fPIC, without RTLD_DEEPBIND:
- SignalHandler works
### As shared lib, without -fPIC:
- Compiling fails with:

```
Linking CXX shared library liblms_lib.so
/usr/bin/ld: libpugixml.a(pugixml.cpp.o): Die Umlagerung von 
libpugixml.a: error adding symbols: Ungültiger Wert
collect2: error: ld returned 1 exit status
make[2]: *** [LMS/lms/liblms_lib.so] Fehler 1
make[1]: *** [LMS/lms/CMakeFiles/lms_lib.dir/all] Fehler 2
make: *** [all] Fehler 2
```
### As shared lib, without -fPIC, with RTLD_DEEPBIND, compile pugixml directly into lmslib:
- SignalHandler works
### As shared lib, without -fPIC, without RTLD_DEEPBIND, compile pugixml directly into lmslib:
- SignalHandler works

**Comment by mherb** [comment]
A quick test using 

``` cpp
auto& handler = lms::SignalHandler::getInstance();
logger.warn() << std::hex << "0x" <<  size_t(&handler);
```

shows that singletons work fine using a shared lib, whereas using a static lib, each module has its own singleton (which obviously makes sense giving that lmslib is linked statically into each module).

Thus going with a shared lib seems to be the only feasible option (other than header-only). As DEEPBIND does not seem to make any difference according to your evaluation (and it is a non-standard linux extension anyway), I do not see any benefit from using the DEEPBIND option.
