### ISSUE TITLE
Runtime

### ISSUE THREAD

**Issue by Phibedy** [Phibedy/LMS#53]
The current Framework is the default runtime,

use <runtime name="runetime_1"> start,define modules etc </runtime> in configs,
every runtime has it's own executionmanager/cycletime etc.

Each runtime can be run in a different thread, but it's not necessary.
If they aren't run in a different thread we have to add some runtime-balancing to handle (different) cycle-times.

I am not sure about sharing data between those "runtimes".
They could share some parent-DataManager, they both would have their own DataManager, but could access read-access from the parent-DataManager. We could limit it to writeExclusive dataChannels.
If the dataChannel extends "Bufferable", we could buffer it automatically.
Those shared dataChannels wouldn't affect the execution-order of the "reading-runtime". That's why we have to implement the DataChannel class, so we can check if new data is available and get the buffered data

**Comment by syxolk** [comment]
Compiles and works on branch runtime. Still missing:
- ~~Config monitor is broken~~
- ~~Dot export needs a rework~~
- Messaging is now runtime local but should be usable framework-wide
- ~~Runtimes running on main thread~~
- Buffered data channel for inter-runtime communication
- Improve config schema
- ~~Profiler could write to a file~~

**Comment by syxolk** [comment]
- Buffered data channel for inter-runtime communication -> see #61
