### ISSUE TITLE
Improve Module Loader

### ISSUE THREAD

**Issue by syxolk** [Phibedy/LMS#56]
The module loader should be able to locate modules at several places, not only from the current build folder. This could include the following locations:
- `/usr/lib/lms`
- `/usr/local/lib/lms`

The `<libpath>` and `<libname>` tags should be improved accordingly.

**Comment by Phibedy** [comment]
An install-script would be nice to have for modules/libs.
We should add some getLmsVersion in module to get the LMS version which was used to compile the module.
Therefore we should add/use some LMS-Version in LMS.
We could automatically generate debian packages. Some script at downloads LMS + LMS-featured libs and compiles+ installs them would be fine,too. In that case I am not sure how to make sure that all dependencies are fulfilled.
