### ISSUE TITLE
The Great Refactoring

### ISSUE THREAD

**Issue by syxolk** [Phibedy/LMS#60]
![Leonardo](https://img.youtube.com/vi/l6GAcEnr5-I/maxresdefault.jpg)

Once upon a time there was a little software framework. The developers used to care for their little framework and the framework prospered and grew. The users were happy and the developers liked what they did.

But one day, when the project became big and complacent, its classes and functions got spread over the folder structure and namespace hierarchy. No user actually knew which classes to trust and which to reject. The framework became a monster that nobody wanted play with anymore. Only the mighty developers on their thrones of wisdom knew the plain truth. But the developers were merciful with the poor users and so they decided to share their knowledge with the community. How should they do it? It had to be backwards-compatible and easy to maintain at the same time. The developers took their time to think about this puzzle for quite some time and then they came up with a solution.

The developers decided to split the framework in two halves. One half was made of all the good parts the users liked and used so much and the other half consisted of the dangerous and filthy corners of the framework. And so it was done: The public API became well documented and easy-to-understand, while the internal functionality was hidden to the users and became a place without return; Everyone was happy with this decision and they lived happily ever after.
### Public API Classes
- `lms::Any`
- `lms::DataChannel`
- `lms::ReadDataChannel`
- `lms::WriteDataChannel`
- `lms::Messaging`
- `lms::Module`
- `lms::ModuleConfig`
- `lms::Serializable`
- `lms::Inheritance`
- `lms::extra::PrecisionTime`
- Everything in `lms::logging`

Everything else is considered private API and will be moved to namespace `lms::internal` and folder `lms/internal`.
### Class Renaming
- `lms::extra::PrecisionTime` -> `lms::Time`
- `lms::ModuleConfig` -> `lms::Config` (Services will be able to use configs.)
### Module Life-cycle
- `bool onInit()`
- `bool onCycle()`
- `void onDestroy()`
- `void onConfigsChanged()`
### Service Life-cycle
- `bool onInit()`
- `void onDestroy()`
- `void onConfigsChanged()`
### XML configs
- `<framework>` -> `<lms>`
- `<executionType>NEVER_MAIN_THREAD</executionType>` becomes default
- `<executionType>ONLY_MAIN_THREAD</executionType>` -> `<mainThread />`

**Comment by Phibedy** [comment]
Have fun :+1:  :)
