### ISSUE TITLE
Framework supported module logging

### ISSUE THREAD

**Issue by syxolk** [Phibedy/LMS#69]
The Framework should provide methods returning the preferred path for logger modules like image_logger, image_loader, channel_serializer ...

``` c++
std::string getLogFile();
std::string getLogDir();
```

There will be command line options activating all logger or loader modules.

```
./lms --save
./lms --load <path>
```

For `--save`, LMS will create a directory `<logPath>/<currentDate>`. The `getLogFile()`  method will then return `<logPath>/<currentDate>/<moduleName>.log`. The `getLogDir()` method will return `<logPath>/<currentDate>/<moduleName>`.

For `--load <path>`, LMS will return `<logPath>/<path>/<moduleName>.log` in `getLogFile()` and `<logPath>/<path>/<moduleName>` in `getLogDir()`.

**Comment by mherb** [comment]
:+1:
