### ISSUE TITLE
Create install-script

### ISSUE THREAD

**Issue by Phibedy** [Phibedy/LMS#7]
As modules/libs are just added via git clone in the external/[modules,libraries] directory it would be easy to write a script that does the job:
- config:
  - list of modules and libraries (list of git repos)
- script could be written using shell-files. Maybe some other should be prefered to run it on win and linux
  - It would update the repos using pull and if they haven't been cloned yet clone them

**Comment by syxolk** [comment]
Created [pull_repos.sh](https://github.com/Phibedy/LMS/commit/0023212fb44be172394040a9606e1272c354bc84) and [fetch_repos.sh](https://github.com/Phibedy/LMS/commit/bbc392cc529a0f325fb18c4f7f38d604fc0e99e7) scripts that pull/fetch all modules and libraries. Use them from inside your build folder.

**Comment by syxolk** [comment]
Not needed anymore, see config repos :-(
