### ISSUE TITLE
Thoughts on LMS 2.0

### ISSUE THREAD

**Issue by syxolk** [Phibedy/LMS#72]
### Statement of problem

Currently one of the biggest issues causing instability are modules triggering segfaults. They leave the whole framework in an uncertain state and the only real solution is to shutdown the process and restart it.

Since there is no watchdog to look over the mess afterwards, you won't even get a message when it stops working. Modules may not be cleaned up properly, letting file descriptors open and causing hard resets of network and hardware connections.
### Bad solution

Make every data channel serializable and send them via TPC to other LMS instances.
- Pro: Every module can be in its own process and even on different machines.
- Con: I don't like serialization when it comes to performance. (Most modules only take a few microseconds to execute. Sending data channels to other processes will take a lot of time compared to that.)
### Suggested solution

This may be circumvented by extensive use of `fork`, shared memory, shared mutex and unix domain sockets. The main process is nothing more then a delegate that forwards commands to child processes and manages common resources and services like logging, messaging and inter-runtime communication.

Each runtime is forked from the 'main process'. The newly created child process then establishes a unix socket to its parent and sends logging messages and profiling data. When the runtime segfaults the main process will get this information immediately (with `wait`) and can react accordingly by restarting it (or doing something else).

Single modules may be forked as well and could use shared memory for data channels. This is easy for plain structs but could be hard for std::vector and friends (All allocations must stay on the shared memory).
- [Shared mutex](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutexattr_getpshared.html)
- [Shared mutex example](http://stackoverflow.com/questions/20325146/share-condition-variable-mutex-between-processes-does-mutex-have-to-locked-be)
- [Shared memory](http://stackoverflow.com/questions/21311080/linux-shared-memory-shmget-vs-mmap)
- [mmap](http://stackoverflow.com/questions/4935627/c-language-how-to-share-a-struct-or-if-not-possible-an-array-between-parent?rq=1)
- [Pipes](http://tldp.org/LDP/lpg/node11.html)

I'm still not sure if its worth the work that has to be done. LMS 2.0 will be postponed after the CC 2016.

**Comment by Phibedy** [comment]
**Bad solution:**
I don't like it at all

**Suggested solution:**
I like it but if we really want to add this we should use [boost](http://www.boost.org/doc/libs/1_59_0/doc/html/interprocess) and add boost as dependency for lms. Atm I really like that lms is "standalone" but the [allocators_containers](http://www.boost.org/doc/libs/1_58_0/doc/html/interprocess/allocators_containers.html) seems to be quite useful.

**Suggested solution light:**
Only fork runtimes, forked runtimes only can communicate with other runtimes via datachannels that are serializable. In that case boost would be useful, too, but as not that much has to be done I don't necessarily want it.

**###########################Other Thoughts###########################**
**Dependencies**
We should discuss if we want to have dependencies. There are a lot of libraries that would be useful for us (boost, boost, boost,...,boost)

**Cereal**
We could use the Cereal define in isSerializable() to auto-serialize simple types or serialize types that are known to cereal. We wouldn't need to extend lms::Serializable.

**PugiXML**
We could remove pugixml from our src and set it as a dependency

**Networking**
We could add some communication between two frameworks. Like SocketData but with error-codes, commands etc.

**Comment by Phibedy** [comment]
ups :dancer:

**Comment by syxolk** [comment]
_By @mherb:_

It should be possible to combine several modules, services and libraries in to a single repository.

Advantage:
- Modules, services and libraries that belong together, will be together by default (less dependencies).
  The image_logger module will always be dependent on the imaging library, and usually you will want to have the image_logger module when you already have imaging.
- Less dynamic libs to be compiled and linked.

We need to improve the module/service interface. The `getInstance` method must somehow return different values depending on a given parameter.

**Comment by Phibedy** [comment]
Mixing libraries and modules would be quite difficult.

**Comment by Phibedy** [comment]
#89

**Comment by Phibedy** [comment]
We may implement #89

**Comment by Phibedy** [comment]
Hier geht es weiter :) #94
